# Use the official Ubuntu 20.04 as a base image
FROM ubuntu:20.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install common tools
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    curl \
    wget \
    git \
    zip \
    unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY cli_download.sh /download.sh
RUN /download.sh
